workspace:
  base: /go
  path: src/logmonitor

pipeline:
  build:
    image: golang
    commands:
      - go build
      - go test ./handler

  deploy:
    image: logmonitor_logmonitor
    ports:
     - "7101:7101"

branches: master
