server_ip: "0.0.0.0"
server_port: "7101"

enable_log_monitor: false
log_monitor_url: "http://localhost/logmonitor/error"

wx_corp_id: "ww603e9c74b17168fc"
wx_corp_secret: "ZOl11Mk0pVAsa9LtfWBW_dyhvuHwFJcgqpv7zy8PcKA"
wx_corp_agent: 1000002

monitor_time: 5
monitor_threshold: 10
monitor_cooldown: 15
